### ISSUE TITLE
api user

### ISSUE THREAD

**Issue by tabsl** [OXIDprojects/admin_2_0#3]
authorization with oauth, but ...

a) all users ?
b) only admin users ?
c) new tinyint field to check: api -> yes / no ?

any suggestions?

**Comment by jkrug** [comment]
Hi,
a+b) just admin users. Otherwise the competitor could register in shop and gets access via the API.
c) good idea!

**Comment by tabsl** [comment]
hm then c) is enough, whether admin user or not?

**Comment by jkrug** [comment]
Hm, could be seen like both. So thats up to you. ;-)

**Comment by tabsl** [comment]
see: https://github.com/OXIDprojects/admin_2_0/issues/4
